---
title: "protofolio"
output: html_document
date: "2024-02-14"
---

```{r}
library(tidyverse)
library(spotifyr)
```


```{r}
pink <- get_playlist_audio_features("", "6en0qrhjID8C3mNSDNvGBQ")
black <- get_playlist_audio_features("", "3cLIerxTI8QvYPsGtr70Ub")
```

```{r}
awards <-
  bind_rows(
    pink |> mutate(category = "Pink"),
    black |> mutate(category = "Black")
  )
```

```{r}
awards |>
  ggplot(aes(x = energy)) +
  geom_histogram(binwidth = 0.1) +
  facet_wrap(~category)
awards |>
  ggplot(aes(x = category, y = energy)) +
  geom_boxplot()
awards |>
  ggplot(aes(x = category, y = energy)) +
  geom_violin()
```
```{r}
pink |> ggplot(aes(x = valence, y = energy)) + geom_point() + geom_smooth()
black |> ggplot(aes(x = valence, y = energy)) + geom_jitter() + geom_smooth()
```
```{r}
awards |>                    # Start with awards.
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  ) |>
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = energy,
      size = loudness,
      colour = mode
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    aes(
      x = valence,
      y = energy,
      label = label
    ),
    data = 
      tibble(
        label = c("STEAM WALTZ", "Darkness and Scattered Light"),
        category = c("Black", "Pink"),
        valence = c(0.104, 0.0339),
        energy = c(0.992, 0.00166)
      ),
    colour = "black",         # Override colour (not mode here).
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical center of label with the point.
    nudge_x = 0.02            # Nudge the label slightly right.
  ) +
  facet_wrap(~ category) +    # Separate charts per playlist.
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),   # Use grid-lines for quadrants only.
    minor_breaks = NULL       # Remove 'minor' grid-lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),
    minor_breaks = NULL
  ) +
  scale_colour_brewer(        # Use the Color Brewer to choose a palette.
    type = "qual",            # Qualitative set.
    palette = "Paired"        # Name of the palette is 'Paired'.
  ) +
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud.
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Valence",
    y = "Energy",
    colour = "Mode"
  )
```


